index:
    path: /
    controller: App\Controller\GestorController::index

app_articulo_ver:
    path: /articulo/{id}
    controller: App\Controller\GestorController::verArticulo
    requirements:
      id: '\d+'

app_nuevo_articulo:
    path: /articulo/nuevo
    controller: App\Controller\GestorController::nuevoArticulo

app_articulo_creado:
    path: /articulo/creado
    controller: App\Controller\GestorController::articuloCreado

app_articulo_editar:
  path: /articulo/editar/{id}
  controller: App\Controller\GestorController::editarArticulo

app_articulo_borrar:
    path: /articulo/borrar/{id}
    controller: App\Controller\GestorController::eliminarArticulo