index:
    path: /
    controller: App\Controller\GestorController::index

app_articulo_ver:
    path: /articulo/{id}
    controller: App\Controller\GestorController::verArticulo
    requirements:
      id: '\d+'

app_articulo_pdf:
    path: /articulopdf/{id}
    controller: App\Controller\GestorController::verArticuloPDF
    requirements:
      id: '\d+'

app_articulo_categoria:
    path: /articuloCategoria/{idCat}
    controller: App\Controller\GestorController::articulosPorCategoria
    requirements:
      idCat: '\d+'

app_articulo_idioma:
    path: /articuloIdioma/{id}
    controller: App\Controller\GestorController::articulosPorIdioma
    requirements:
      id: '\d+'

app_articulo_autor:
    path: /articuloAutor/{id}
    controller: App\Controller\GestorController::articulosPorAutor
    requirements:
      id: '\d+'

app_nuevo_articulo:
    path: /articulo/nuevo
    controller: App\Controller\GestorController::nuevoArticulo

app_articulo_creado:
    path: /articulo/creado
    controller: App\Controller\GestorController::articuloCreado

app_articulo_editar:
  path: /articulo/editar/{id}
  controller: App\Controller\GestorController::editarArticulo

app_articulo_borrar:
    path: /articulo/borrar/{id}
    controller: App\Controller\GestorController::eliminarArticulo

#Usuario
app_perfil_ver:
    path: /usuario/{id}
    controller: App\Controller\UsuarioController::mostrarPerfil
    requirements:
      id: '\d+'

app_perfil_editar:
    path: /usuario/editar/{id}
    controller: App\Controller\UsuarioController::editarUsuario
    requirements:
      id: '\d+'

#Admin
app_ver_articulos:
    path: /admin/articulos
    controller: App\Controller\AdminController::vistaArticulos

app_borrar_articulo_admin:
    path: /admin/articulo/borrar/{id}
    controller: App\Controller\AdminController::eliminarArticulo

app_ver_usuarios:
    path: /admin/usuarios
    controller: App\Controller\AdminController::vistaUsuarios

app_borrar_usuario_admin:
    path: /admin/usuario/borrar/{id}
    controller: App\Controller\AdminController::eliminarUsuario

app_nueva_categoria:
    path: /admin/categoria
    controller: App\Controller\AdminController::nuevaCategoria

app_nuevo_idioma:
    path: /admin/idioma
    controller: App\Controller\AdminController::nuevoIdioma